Repository syndesisio/syndesis-qe, pull requests merged in 2018-11, with the labels that each got.

#627 [ui][new] API Provider tests
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ChooseOperation.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ApiProviderWizard.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/NameApiProviderIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/swagger/connectors/simple-string.json
  ui-tests/src/test/resources/swagger/connectors/todo.json
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
Labels: approved

#642 Introduce GitHub issue tag
  README.md
  ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java
Labels: approved

#646 Allow overriding maven repo when running with upstream
  README.md
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: WIP, approved, status/review-requested

#626 ui: added tests for OAuth Settings
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/other/settings-oauth.feature
Labels: approved

#648 [ui][fix] fix data-buckets test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#649 [ui][fix] fix data-buckets test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#647 [Operator] Undeploy syndesis before cleaning namespace
  README.md
  pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved, status/review-requested

#654 [FUSEQE-2430] Fix oracle12 test
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#653 [FUSEQE-2542] Fix upgrade using operator
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#650 [ui][update] add dynamic wait in 3scale test for syndesis-server restart
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: status/review-requested

#651 [ui][update] add dynamic wait in 3scale test for syndesis-server restart
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: status/review-requested

#645 fix loging on stagings
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: status/review-requested

#655 [FUSEQE-2430] Fix oracle12 1.5
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#644 [ui][new] API Provider tests
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ChooseOperation.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ApiProviderWizard.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/NameApiProviderIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/swagger/connectors/simple-string.json
  ui-tests/src/test/resources/swagger/connectors/todo.json
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
Labels: approved

#658 Add GitHub issue tags
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved, status/review-requested
