Repository syndesisio/syndesis-qe, pull requests merged in 2018-05, with the labels that each got.

#452 fix(circleci): Update browser deps
  .circleci/config.yml
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved, status/review-requested

#447 [ui-tests] Api connector - invalid swagger test
  ui-tests/src/test/java/io/syndesis/qe/pages/WizardPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewEditConnectorDetails.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/WizardSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature
  ui-tests/src/test/resources/swagger/connectors/invalid/kie-server-swagger.json
Labels: approved, status/review-requested

#451 [ui][new] mqtt test
  README.md
  pom.xml
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/mqtt/MqttUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/mqtt/Receiver.java
  utilities/src/main/resources/templates/syndesis-amq.yml
Labels: approved, status/review-requested

#453 [ui][update] Slack test updated
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved, status/review-requested

#472 [ui][fix] adding sleep in connection creation so jenkins has more tim…
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#473 [ui][update] Added jenkins delay property
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: status/review-requested

#449 [relates #445] Mysql
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/DbWrapper.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: status/review-requested

#454 [ui][new] Logout test
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/other/login-logout.feature
Labels: approved, status/review-requested

#446 Issue 318 upgrade
  rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  rest-tests/src/test/resources/upgrade/99-change-ui-config.sh
  rest-tests/src/test/resources/upgrade/up-98-template.js
  rest-tests/src/test/resources/upgrade/up-99-template.js
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: approved, status/review-requested

#482 [FUSEQE-1032] Add a note about GHPRB to Readme
  README.md
  rest-tests/README.md
Labels: approved

#476 [ui-tests] Form filling - new Form.fillBy methods
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/CoupledForm.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/configure/ConfigureConnection.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/NameConnectionSteps.java
  ui-tests/src/test/resources/features/connections/connections.feature
Labels: approved, status/review-requested

#477 [ui][new] OAuth flow test
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/OAuthSettingsComponent.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#483 chore: Move to next devel version
  pom.xml
Labels: approved, status/review-requested

#484 [Cleanup] Remove log
  rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: approved, status/review-requested

#485 [relates #1041] Rest smoke test
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntermediateSteps.java
  rest-tests/src/test/resources/features/smoke.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#486 [ui][refactor] RIP CAMILLE
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/SelectConnectionTypeSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/WizardSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/dashboard/DashboardSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/CreateIntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/ConnectionActionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConfigureStepSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/DetailsSteps.java
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
  ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature
  ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
  ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector-integration.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
  ui-tests/src/test/resources/features/integrations/database-to-database.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
  ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
  ui-tests/src/test/resources/features/integrations/integration-monitoring.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/other/login-logout.feature
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved
