Repository syndesisio/syndesis-qe, pull requests merged in 2018-08, with the labels that each got.

#547 [ui][fix] Fixes for database tests
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#542 [FUSEQE-1425] Stabilize REST + cleanup
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/DbSteps.java
  rest-tests/src/test/resources/features/file-transfer.feature
  rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DropBoxValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsActionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
  utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java
  utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: WIP, approved

#548 [FUSEQE-1425] Fix salesforce + retry login when unsuccessful
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Labels: approved

#550 [FUSEQE-1502] Deploy syndesis via operator by default
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#552 [rest][update] Use only one twitter credentials
  rest-tests/src/test/resources/features/integration-tw-sf.feature
Labels: status/review-requested

#549 [ui][new] adding basic concur connectivity oauth test
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/telegram.feature
Labels: status/review-requested

#555 [ui][fix] Stabilize smoke tests
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
Labels: approved, status/review-requested

#556 [ui][fix] Stabilize webhook test
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved, status/review-requested

#557 [ui][fix] Fix data buckets tests, add extension assert
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/log-connector.feature
Labels: approved, status/review-requested

#558 Update readme file
  README.md
  manual/sf2db.feature
  manual/tw2sf.feature
Labels: approved, status/review-requested

#562 [ui][fix] Update cucumber options to new format
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
Labels: approved, status/review-requested

#560 [FUSEQE-1585] Add basic service-now API wrapper
  utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
  utilities/src/main/java/io/syndesis/qe/servicenow/model/Incident.java
  utilities/src/main/java/io/syndesis/qe/servicenow/model/IncidentRecordList.java
  utilities/src/main/java/io/syndesis/qe/servicenow/model/IncidentSingleResponse.java
  utilities/src/main/java/io/syndesis/qe/servicenow/model/LinkValue.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: WIP, approved, status/review-requested

#563 [ui][fix] Fix log test, update log out test
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/log-connector.feature
Labels: approved, status/review-requested

#564 [ui][fix] Add dynamic wait when checking for existing extension
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
Labels: approved, status/review-requested

#567 [ui][fixes] Jenkins fixes
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/integrations/Imported-integration-another-instance-export.zip
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
Labels: approved, status/review-requested

#566 [ui][fixes] Jenkins fixes
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/integrations/Imported-integration-another-instance-export.zip
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
Labels: approved, status/review-requested

#568 FUSEQE-1532
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#565 [FUSEQE-1585] Add update incident
  utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: approved

#553 [rest-test] Add timer connector tests
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationSteps.java
  rest-tests/src/test/resources/features/soak-deployment.feature
  rest-tests/src/test/resources/features/timer-connector.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java
Labels: approved, status/review-requested

#570 [ui][update] update telegram manual test steps
  ui-tests/src/test/resources/features/integrations/telegram.feature
Labels: approved, status/review-requested

#569 [ui][update] update telegram manual test steps
  ui-tests/src/test/resources/features/integrations/telegram.feature
Labels: approved, status/review-requested

#573 Update readme file - install syndesis from testsuite
  README.md
Labels: approved, status/review-requested

#574 Update readme file - install syndesis from testsuite
  README.md
Labels: approved, status/review-requested

#571 [Prod] Fail when prod repository is not set
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#572 [Prod] Fail when prod repository is not set
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#575 [ServiceNow] add connector UI test
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/resources/features/integrations/service-now.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
Labels: status/review-requested

#554 [ui][new] adding basic concur test
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/concur.feature
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved, status/review-requested

#576 [ui][new] Adding new concur test
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/concur.feature
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: status/review-requested
