Repository syndesisio/syndesis-qe, pull requests merged in 2018-10, with the labels that each got.

#604 [ui][update] enable concur oauth connector test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: status/review-requested

#605 [ui][fix] fix slack connection
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Labels: approved

#607 [README] update readme
  README.md
Labels: approved

#606 [ui][fix] fix slack connection
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Labels: approved

#584 [ui][new] Api connector flow test
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/api-client-connector-integration.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
Labels: approved, status/review-requested

#585 [ui][new] Api connector new flow test
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/api-client-connector-integration.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
Labels: approved, status/review-requested

#610 [README] - Add info about hotswap
  README.md
Labels: approved

#611 [ui][disable] disable github afterhook due to ENG not liking our labels
  ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java
Labels: approved, status/review-requested

#612 [README] - add more information to Advanced debugging
  README.md
Labels: approved

#608 [ui][fix] fix concur oauth validation
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: status/review-requested

#609 [ui][fix] fix concur oauth validation
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: status/review-requested

#614 [ui][fix] apicurito updated to new version
  ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: status/review-requested
