Repository syndesisio/syndesis-qe, pull requests merged in 2018-09, with the labels that each got.

#579 [ui][new] adding test for Slack consumer
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/SlackSteps.java
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Labels: approved, status/review-requested

#580 [Ignore] Ignore tests with @ignore tag
  rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
  rest-tests/src/test/resources/features/soak-deployment.feature
Labels: approved, status/review-requested

#583 [SF] Check for create responses
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/AmqSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
Labels: approved, status/review-requested

#582 [SF] Check for create responses
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/AmqSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
Labels: approved, status/review-requested

#587 [fix] SlackConnector and Slack test was updated
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Labels: approved, status/review-requested

#588 [ui][fixes] Making tests more stable
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/resources/features/integrations/service-now.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
Labels: approved, status/review-requested

#589 [ui][new] Extending concur tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/resources/features/integrations/concur.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#581 [ServiceNow] add connector UI test
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/resources/features/customizations/connectors/timer-connector.feature
  ui-tests/src/test/resources/features/integrations/service-now.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: status/review-requested

#591 [rest][fix] integration builder invocation changed
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
Labels: approved

#595 Add SAR_PROJECT argument for template deployments
  README.md
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#586 Update readme
  README.md
Labels: approved, status/review-requested

#592 [ui][fix] fix api connector tests
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
Labels: approved, status/review-requested

#598 [ui][fix] add dynamic wait for data mapper
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
Labels: approved, status/review-requested

#599 [rest][fix] add missing flow id + name to filter
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntermediateSteps.java
Labels: approved

#593 [ui][fix] fix mysql timeout
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: approved, status/review-requested

#602 fix readme - how to run multiple scenarios via PR
  README.md
Labels: approved, status/review-requested

#600 [ui][fix] do not fail the test when unknown oauth option is found
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved, status/review-requested

#603 fix readme - how to update submodules
  README.md
Labels: approved, status/review-requested

#596 [rest][new] Added s3 delete object action, fixed bucket removal after…
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/S3Steps.java
  rest-tests/src/test/resources/features/file-transfer.feature
  rest-tests/src/test/resources/features/integration-s3-to-s3.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
Labels: approved, status/review-requested
