Repository syndesisio/syndesis-qe, pull requests merged in 2019-11, with the labels that each got.

#1227 [SNS] Refactor SNS from DB to AMQ
  rest-tests/src/test/resources/features/integration-sns.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SNSValidationSteps.java
Labels: approved, status/review-requested

#1228 [Kafka] Fix kafka cleanup
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
Labels: status/review-requested

#1230 Bump Syndesis version to 1.9
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsEndpoint.java
Labels: approved, status/review-requested

#1231 [UI] - fix apicurio tests
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Labels: approved, status/review-requested

#1232 Updated tests with Contact table
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/email.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/jira.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/telegram.feature
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
Labels: approved, status/review-requested

#1220 Fixed small issues with PublicApi tests
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
  utilities/src/main/java/io/syndesis/qe/publicapisteps/EnvironmentsPublicApiSteps.java
Labels: approved, backport 1.8.x, status/review-requested

#1234 [SQS] Retry purge queue after delay if there is some already in progress
  utilities/src/main/java/io/syndesis/qe/utils/SQSUtils.java
Labels: approved, status/review-requested

#1238 google-sheets: add basic chart test
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved, status/review-requested

#1237 [ui] stabilized api provider tests on OCP4
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
Labels: approved, status/review-requested

#1244 Test support
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/resources/syndesis-minimal.yaml
Labels: approved

#1203 [ui] api-provider modification still had some integrations running
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved

#1242 validate credentials from @smoke removed
  ui-tests/src/test/resources/features/connections/connections.feature
Labels: approved

#1240 fix in telegram test
  ui-tests/src/test/resources/features/integrations/telegram.feature
Labels: approved

#1245 [SnoopSelectors] Rename property for snoopselectors
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#1246 [Deploy] Add info about cluster and namespace
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1249 [FUSEQE-7042][FIX] - wait till integrations are deleted
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
Labels: approved, status/review-requested

#1247 Smoke fix for Chrome
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
Labels: approved, status/review-requested

#1243 [FUSEQE-6941] - reproducers for ENTESB-11415, ENTESB-11447, ENTESB-11…
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetail.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/InvokeSql.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/ConnectionActionSteps.java
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
Labels: status/review-requested

#1250 [FUSEQE-7043] - updated duplicate integration names
  rest-tests/src/test/resources/features/integration-lifecycle.feature
  rest-tests/src/test/resources/features/integration-sns.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/email.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/odata.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
Labels: approved, status/review-requested

#1252 [FUSEQE-7046] Fix Amq to rest scenario
  utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
  utilities/src/main/resources/templates/syndesis-default-amq-service.yml
Labels: approved, status/review-requested

#1251 [FUSEQE-7042] - Fix smoke test
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetail.java
Labels: approved, status/review-requested

#1253 [soak-test] fix delay problem
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/IntermediateSteps.java
  rest-tests/src/test/resources/features/soak-deployment.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
Labels: approved, status/review-requested

#1254 [rest-timer] fix assert
  rest-tests/src/test/resources/features/timer-connector.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
Labels: approved, status/review-requested
