Repository syndesisio/syndesis-qe, pull requests merged in 2019-09, with the labels that each got.

#1074 [FUSEQE-5921] Move box folder id to credentials
  utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
Labels: approved, status/review-requested

#1052 [ui][fix] Changed template to work on React UI
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/TemplateSteps.java
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/templates/code_editor_test.txt
Labels: approved, status/review-requested

#1075 [FUSEQE-5956] Fix twitter to salesforce basic scenario
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
Labels: status/review-requested

#1078 Migrate open GH issues to ENTESB anotation
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
  ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature
  ui-tests/src/test/resources/features/other/publicapi/export-import.feature
Labels: approved, status/review-requested

#1079 [readme-correction] Small correction to make text more clear
  README.md
Labels: approved

#1080 [fix] adapted latest changes in ContinuousDeliveryEnvironment
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved, status/review-requested

#1081 [FUSEQE-5902] Fix rest rests
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
Labels: approved

#1072 reproducer for gh-5559
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java
  ui-tests/src/test/resources/features/integrations/odata.feature
Labels: status/review-requested

#1089 Fix upgrade image check in operator for RHEL 7 and 8
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
Labels: approved, backport 1.7.x, status/review-requested

#1088 Fix @integrations-check-starting-status tests
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/CreateIntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/integration-status.feature
Labels: approved, status/review-requested

#1093 [FUSEQE-5597] Annotate long running features
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/integration-sqs.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/odata.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#1092 [FUSEQE-5828] - Update Public API tests
  rest-tests/src/test/resources/features/publicapi/environments.feature
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  ui-tests/src/test/resources/features/other/publicapi/export-import.feature
  utilities/src/main/java/io/syndesis/qe/publicapisteps/EnvironmentsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved

#1084 Fix different credentials working for email connector
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
  ui-tests/src/test/resources/features/integrations/email.feature
Labels: approved

#1086 [FUSEQE-5830] - updated salesforce UI tests
  rest-tests/src/test/resources/features/integration-kafka.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Labels: status/review-requested

#1058 [rest][1.7.x] - PublicOauth template fixes
  rest-tests/src/test/resources/features/publicapi/environments.feature
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdDialogSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
Labels: approved

#1077 [ui] - fixed slack connector and created the channels for every test
  ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/slack/ReadMessages.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConfigureStepSteps.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/integrations/Imported-integration-another-instance-export.zip
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved

#1098 [FUSEQE-6013] - updated Metrics tab selectors
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
Labels: approved, status/review-requested

#1099 [FUSEQE-6030][ui][update] add data mapper integration into smoke tests
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
Labels: approved, status/review-requested

#1104 [ui] update maintainers of features
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/datashapes.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  ui-tests/src/test/resources/features/integrations/telegram.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/other/3scale.feature
  ui-tests/src/test/resources/features/other/login-logout.feature
  ui-tests/src/test/resources/features/other/settings-oauth.feature
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved, status/review-requested

#1105 [1.7.x] - Fix namespace for service account
  utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
Labels: approved, status/review-requested

#1106 [REST] - Fix namespace for service account
  utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
Labels: approved, status/review-requested

#1100 [fix] post existing - affected by ENTESB-11675, and added 2 waits
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#1107 [UI] Create screenshot even if the test fails in background
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
Labels: approved

#1108 [Server] Print useful info when something went wrong with the server
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#1097 fix service-now tests
  ui-tests/src/test/resources/features/integrations/service-now.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/servicenow/model/Incident.java
Labels: approved, status/review-requested

#1073 [FUSEQE-5863] Add Jira issue hooks
  README.md
  pom.xml
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
  utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
  utilities/src/main/java/io/syndesis/qe/issue/IssueState.java
  utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java
  utilities/src/main/java/io/syndesis/qe/utils/IssueHooksUtils.java
Labels: approved, status/review-requested

#1119 [FUSEQE-6153] Temporary disable upgrade tests
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
Labels: approved, status/review-requested

#1101 [FUSEQE-6043] Deploy operator from generated resources
  README.md
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/resources/syndesis-minimal.yaml
Labels: approved, status/review-requested

#1120 [FUSEQE-6043] Fix for latest operator tag
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1122 [FUSEQE-6043] Further fix for new install
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1123 Update README.md
  README.md
Labels: approved, status/review-requested

#1121 [FUSEQE-6030] Fix flaky smoke test
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
Labels: approved, status/review-requested

#1117 Fix Conditional flow tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/ConditionalFlows.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConditionalFlowsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
Labels: approved, status/review-requested

#1124 Tweak minimal CR
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/resources/syndesis-minimal.yaml
Labels: approved

#1115 fix: google sheet stale elements fix
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved, status/review-requested

#1102 Happy path API Provider error handling
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/swagger/connectors/todo.json
Labels: approved, status/review-requested

#1096 [FUSEQE-5979] Part 2, update form fill with dropdown
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
Labels: approved, status/review-requested

#1055 Remove gh-6141 workaround
  utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
Labels: approved

#1125 [FUSEQE-5666] Add test for box download datamapper
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/resources/features/integration-box.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
Labels: approved, status/review-requested

#1126 [Deploy] Use syndesis url as route if set
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1129 Fix installation with prod operator
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1128 Added enum entry for AWS DDB
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1131 [Operator] Fix operator name / tag parsing
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1133 [FUSEQE-6268] - Fixed Metrics scenario
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
Labels: approved
