Repository syndesisio/syndesis-qe, pull requests merged in 2019-07, with the labels that each got.

#984 [ui][react] Fix google calendar tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/google/EventForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/google/GetSpecificEvent.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleCalendarSteps.java
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
Labels: approved, status/review-requested

#990 [UI] - Reproducer for showing WebHook URL in UI
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/DetailsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved, status/review-requested

#989 Email migration
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
  ui-tests/src/test/resources/features/integrations/email.feature
Labels: approved, status/review-requested

#980 [FUSEQE-4853] Add a simple reachability check
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: approved, status/review-requested

#987 [FUSEQE-4857] Changes needed to work with newer openshift-client
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ProdValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/HTTPEndpointsTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/IrcTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/JmsClient.java
  utilities/src/main/java/io/syndesis/qe/utils/JmsClientManager.java
  utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/TodoUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved

#992 [ui][fix] update connectors creation to use OAuth
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
Labels: approved, status/review-requested

#993 [Reachability] Close the response body to prevent leaked connections
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: approved, status/review-requested

#997 [FUSEQE-4982] Don't expect PG_EXPORTER namespace
  template/generate.sh
  template/vars
Labels: approved

#995 [ui][fix] fix api client connector delete scenario
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
Labels: approved, status/review-requested

#998 [ui][fix] add next button click where required
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
Labels: approved, status/review-requested

#996 [ui][fix] fix amq-to-rest host property
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
Labels: approved, status/review-requested

#999 [ui] Fix db-to-db-with-extension
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
Labels: approved, status/review-requested

#1000 updated information about running syndesis tests with chrome
  README.md
Labels: approved

#1002 Fixed wrong db.schema name from dballocator
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved

#1005 [ui][fix] fix smoke tests
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
Labels: approved, status/review-requested

#991 [REST]Fix namespace in deleting cluster role bindings method
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
Labels: approved, status/review-requested

#982 [UI] fix gmail integration tests with new oauth connection creation
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
  ui-tests/src/test/resources/features/integrations/gmail.feature
Labels: approved, status/review-requested

#1006 [UI] fix date selector in Activity tab
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
Labels: approved, status/review-requested

#1007 [ui][fix] maximalize firefox on login and OAuth
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: status/review-requested

#1001 [FUSEQE-4983][FUSEQE-5007][FUSEQE-5008] OAuth proxy / komodo / quay
  README.md
  template/generate.sh
  template/prod.template.yml
  template/vars
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#969 [ui][new] Conditional flow feature
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
Labels: approved, status/review-requested

#1010 [FUSEQE-4322] telegram feature migration to react ui
  ui-tests/src/test/resources/features/integrations/telegram.feature
Labels: approved, status/review-requested

#1011 [ui][fix] Workaround firefox file upload
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/UploadFile.java
Labels: approved, status/review-requested

#1015 [UI] update metrics and activity tests according to fixed issues
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
Labels: approved, status/review-requested

#1009 [ui][fix] correctly fill todo host URL
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
Labels: approved, status/review-requested

#1018 Apicurito fixes rebase
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: approved, status/review-requested

#1020 Templates
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
  rest-tests/src/test/resources/upgrade/prod/vars
  template/prod.template.yml
Labels: approved, status/review-requested

#1017 [ui][update] update connection creation
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1003 integration status feature migration
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/integration-status.feature
Labels: approved, status/review-requested

#1019 [ui][fix] fix import-export tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/DragAndDropFile.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
Labels: approved, status/review-requested

#1012 reproducers for gh-5533 and gh-5386
  ui-tests/src/test/resources/features/integrations/odata.feature
Labels: approved, status/review-requested

#1025 Add oauth 4.0.0 to the template for PublicApi tests
  template/prod.template.yml
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved, status/review-requested

#1022 [Upgrade] Bring back secret in prod upgrade
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, status/review-requested

#1024 [ui][fix] fix dropbox creation in data buckets
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#1026 [ui][stabilize] add wait to stabilize form filling
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
Labels: approved, status/review-requested

#1027 [ui][stabilize] stabilize OAuth connection validation test
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1008 [FUSEQE-5032] Re-enable upgrade tests + refactor
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  ui-tests/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: status/review-requested

#1031 [ui][fix] fix api client connector root selector
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
Labels: approved, status/review-requested

#1013 [ui][fix] API Provider rebase on react UI
  ui-tests/pom.xml
  ui-tests/src/test/java/io/syndesis/qe/debug/AnnotationPlugin.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ChooseOperation.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ApiProviderWizard.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/NameApiProviderIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved

#1034 google-sheets: fix create spreadsheet
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved

#1032 [ui][stabilize] stabilize webhook JSON specification
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/integrations/webhook-db.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
Labels: approved, status/review-requested

#1030 [ui][new] test integration input datashape refresh
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/datashapes.feature
Labels: status/review-requested

#1033 [ui][fix] fix salesforce OAuth validation
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1035 [ui][fix] fix dataBucket tests
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#1036 [Template] Sync with fuse-online-install
  template/prod.template.yml
Labels: approved, status/review-requested

#1038 Make sure nexus is used
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1041 [fix][ui] webhook-api-connector-list-tasks
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
Labels: approved, status/review-requested

#1039 [Upgrade] Prod upgrade changes
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
Labels: approved, status/review-requested

#1044 [ui][stabilize] stabilize conditional flow and cicd features
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature
Labels: approved, status/review-requested

#1045 Make _really_ sure nexus is used
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1043 Added test for API Provider with conditional flow
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved, status/review-requested

#1040 [UI][fix] - logout page on OCP4
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1046 [FUSEQE-5318] Add dependency on syndesis-cli for upgrade tests
  pom.xml
  rest-tests/pom.xml
Labels: approved, status/review-requested

#1037 New odata svc changes
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java
  utilities/src/main/resources/templates/syndesis-wildfly.yml
Labels: approved, status/review-requested
