Repository syndesisio/syndesis-qe, pull requests merged in 2019-10, with the labels that each got.

#1135 Use correct version for 1.7.x
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#1136 [FUSEQE-5666] Assure that the poll will happen only once at start
  rest-tests/src/test/resources/features/integration-box.feature
Labels: approved, status/review-requested

#1132 Annotated the SQL dropdown issue
  ui-tests/src/test/resources/features/integrations/import-edit.feature
Labels: approved, status/review-requested

#1130 [ui] Set value of dropbox upload mode
  ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
Labels: approved, status/review-requested

#1137 [Jira hook] Fix jira hook name
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/utils/IssueHooksUtils.java
Labels: backport 1.7.x, status/review-requested

#1141 Use new syndesis operator binary
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1144 Remove patchImageStreams and importProdImages
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1146 [typo] Fix typo in ENTESB
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved, backport 1.7.x, status/review-requested

#1148 [Template] Remove obsolete template generator
  template/generate.sh
  template/prod.template.yml
  template/vars
Labels: approved, status/review-requested

#1142 [FUSEQE-5449] Batch Update automated test for DB
  ui-tests/src/test/resources/features/integrations/webhook-db.feature
Labels: approved, status/review-requested

#1150 Added annotations for failing tests
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/template.feature
Labels: approved, status/review-requested

#1113 [FUSEQE-6035] Reparation of apicurio tests
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: approved, status/review-requested

#1151 [SQS-SNS] Purge only relevant queues for each test
  rest-tests/src/test/resources/features/integration-sns.feature
  rest-tests/src/test/resources/features/integration-sqs.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SQSValidationSteps.java
Labels: approved, status/review-requested

#1139 [FUSEQE-6286] Fix twitter direct message send
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
Labels: approved, status/review-requested

#1118 Oauth text fix - google calendar
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/other/settings-oauth.feature
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved

#1156 [ui] do not login if already logged in hack
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1143 [FUSEQE-6269] Fixed Slack scenarios
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/slack/ReadMessages.java
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved

#1153 [integration-lifecycle] Allow the integration lifecycle tests
  rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
  rest-tests/src/test/resources/features/integration-lifecycle.feature
Labels: approved, status/review-requested

#1158 [servicenow] fix select from dropdowns
  ui-tests/src/test/resources/features/integrations/service-now.feature
Labels: approved, status/review-requested

#1140 [FUSEQE-5668] Add dynamoDb basic test set
  pom.xml
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DynamoDbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DynamoDbUtils.java
Labels: approved, status/review-requested

#1155 [tw_sf] Fix - dropdown was reintroduced
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/other/support-page.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Labels: approved, status/review-requested

#1157 [UI] Quick fix login page
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1161 [UI] Download drivers only with download-drivers profile
  README.md
  ui-tests/pom.xml
Labels: approved, status/review-requested

#1162 [tw_sf] Fix for second set of credentials
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Labels: approved, status/review-requested

#1149 Conditional flows new tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/ConditionalFlows.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConditionalFlowsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
Labels: approved, status/review-requested

#1163 [ui] Google choose account workaround
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1164 [SQS] Add missing queues to purge
  rest-tests/src/test/resources/features/integration-sqs.feature
Labels: approved, status/review-requested

#1095 Syndesis API discovery by 3scale fix
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/other/3scale.feature
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved

#1159 Add sleep in order to let data mapper fully load
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/resources/features/integrations/odata.feature
Labels: approved

#1166 [FUSEQE-6350] - added delay to the CICD dialog page
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java
Labels: approved, status/review-requested

#1165 [webhook] Fix the webhook regex, to conform to the OCP 4.1. URL format
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved, status/review-requested

#1168 [DB-to-DB] Fix smoke test - remove unnecessary open collection mapping
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
Labels: approved, status/review-requested

#1167 Add wait for operations to fully load (due to OCP 4.1. failures)
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
Labels: approved, status/review-requested

#1116 [FUSEQE-5665] semi-automated testing of jira connector
  pom.xml
  ui-tests/src/test/java/io/syndesis/qe/steps/other/JiraSteps.java
  ui-tests/src/test/resources/features/integrations/jira.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/utils/jira/JiraClientFactory.java
  utilities/src/main/java/io/syndesis/qe/utils/jira/JiraOAuthGetAccessToken.java
  utilities/src/main/java/io/syndesis/qe/utils/jira/OAuthJiraAuthenticationHandler.java
Labels: approved, status/review-requested

#1171 [ui] used new steps for interacting with conditional flow
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved, status/review-requested

#1169 [FIX] Kudu test fix test
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, status/review-requested

#1111 google-sheets: fix tests to work with updated component
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleSheetsValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
Labels: approved, status/review-requested

#1174 service-now: add posibility to run tests in parallel on different browsers
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ServiceNowSteps.java
  ui-tests/src/test/resources/features/integrations/service-now.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
Labels: approved, status/review-requested

#1177 Add ENTESB-11487 annotation and consolidate test
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#1175 [ENTESB-11690] Add reproducer for ENTESB-11690, ENTESB-11640, ENTESB-10194
  rest-tests/src/test/resources/features/integration-edit-dc.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#1178 [FIX] Login logout test fix
  ui-tests/src/test/resources/features/other/login-logout.feature
Labels: approved

#1179 [AMQ] Use label for syndesis-amq to be selectable by broker-amq-tcp svc
  utilities/src/main/resources/templates/syndesis-amq.yml
Labels: approved, status/review-requested

#1173 [FUSEQE-6350][fix] - Fix period time for Slack scenarios
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
Labels: approved, status/review-requested

#1182 Delete one odata scenario - no longer needed
  ui-tests/src/test/resources/features/integrations/odata.feature
  utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
Labels: approved, backport 1.8.x, status/review-requested

#1109 Selector reports
  pom.xml
  ui-tests/pom.xml
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  ui-tests/src/test/java/io/syndesis/qe/debug/AnnotationPlugin.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/ClassTransformerHook.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/SelectorSnooper.java
  ui-tests/src/test/java/io/syndesis/qe/pages/login/MinishiftLogin.java
  ui-tests/src/test/java/io/syndesis/qe/reports/selectors/SelectorUsageInfo.java
  ui-tests/src/test/java/io/syndesis/qe/reports/selectors/SelectorUsageReporter.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ExcludeFromSelectorReports.java
  ui-tests/src/test/resources/templates/data_test_id_template.vm
  ui-tests/src/test/resources/templates/selector_report_template.vm
  ui-tests/src/test/resources/templates/url_report_template.vm
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#1191 fix Name fill before publishing an integration
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
Labels: approved, status/review-requested

#1189 Fixed the mapper step error in which collections to be opened cannot be found
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#1193 Fix waiting for server redeployment
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#1180 google-sheets: fix pivot table test on firefox
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved

#1184 [FIX] FTP to FTP test fix
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
Labels: approved, status/review-requested

#1183 [ui] fixed some failing api provider issues
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/swagger/connectors/todo.json
Labels: approved, status/review-requested

#1194 Fix integrations-odata-create - open data mapper collections
  ui-tests/src/test/resources/features/integrations/odata.feature
Labels: approved

#1199 [UI] Fix login for 4.2
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1200 Fix @integrations-datashapes-input-change-conditional-flow
  ui-tests/src/test/resources/features/integrations/datashapes.feature
Labels: approved, status/review-requested

#1201 [ui][fix] fix @db-insert-multiple-rows test
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
Labels: approved

#1202 [ResetDB] Cleanup openshift resources
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
Labels: approved

#1206 disable oauth calendar test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved

#1198 [Utils] Harden waiting for next pod
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved, status/review-requested

#1207 [Install] Add a check for route condition
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1209 [MQTT] Bump mqtt client version
  pom.xml
Labels: approved, status/review-requested

#1196 GH token description added to most common problems
  README.md
Labels: approved, status/review-requested

#1210 [ui] Fix login to OCP 4 on OpenStack
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1208 [FIX] Apicurito step fix
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Labels: approved

#1211 [Deploy] Print the exception when the test fails in beforeclass
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
Labels: approved

#1212 [TestConfiguration] Catch exception in test configuration constructor
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#1195 fix @integrations-check-starting-status tests
  ui-tests/src/test/resources/features/integrations/integration-status.feature
Labels: approved, status/review-requested

#1214 [ui] Add MongoDB happy path tests
  pom.xml
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java
  ui-tests/src/test/resources/features/integrations/mongodb.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/MongoDb36Template.java
Labels: approved, status/review-requested

#1215 [Route] Fix NPE in checkRoute
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#1216 [Kafka] Bump amq-streams to 1.3.0
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/resources/kafka/kafka-ephemeral.yaml
  utilities/src/main/resources/kafka/strimzi-deployment.yaml
Labels: approved, status/review-requested

#1204 Classes are transformed only when selector reporting is enabled
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/ClassTransformerHook.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/SelectorSnooper.java
Labels: approved, status/review-requested

#1217 [ui] Fix typo in mongo tests
  ui-tests/src/test/resources/features/integrations/mongodb.feature
Labels: approved, status/review-requested

#1218 Fix public oauth image version
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
Labels: approved, status/review-requested

#1219 [Logging] Add error logging to the cases where exception is raised
  utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#1187 [UI] - Updated existing test as reproducer for ENTESB-11474
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/Editor.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/other/integration-info.feature
Labels: approved, status/review-requested

#1222 Add reproducer for ENTESB-11870
  ui-tests/src/test/resources/features/integrations/data-mapper.feature
Labels: approved, status/review-requested

#1224 Fixed logout test on remote OCP4.2
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#1221 [TestSupport] Revert cleaning RCs
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
Labels: approved, status/review-requested

#1225 [IRC] Rework interacting with irc server
  rest-tests/src/test/resources/features/irc.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/IrcValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/IrcTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
Labels: approved, status/review-requested

#1226 [Endpoints] Retry invocations in case of an exception
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/util/RetryingInvocationBuilder.java
Labels: approved, status/review-requested
