Repository syndesisio/syndesis-qe, pull requests merged in 2019-06, with the labels that each got.

#945 [Connection tests] fix buttons in connection tests
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/resources/features/connections/connections.feature
Labels: status/review-requested

#938 [UI] only automatically open unnamed collections on data mapper
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
Labels: approved

#946 [ui][fix] support page feature
  ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved, status/review-requested

#948 Fix servicenow tests
  ui-tests/src/test/resources/features/integrations/service-now.feature
Labels: approved

#941 [ui][fix] get rid of failing old mapping step
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved, status/review-requested

#951 [ui][fix] fix kudu feature
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, status/review-requested

#953 [UI] fix the gmail integration feature with new ui
  ui-tests/src/test/resources/features/integrations/gmail.feature
Labels: approved

#954 [ui][fix] fix 3scale feature
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/other/3scale.feature
Labels: approved, status/review-requested

#956 [ui][fix] fix the rest of the kudu scenarios
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, status/review-requested

#957 [fixaton] changed oauth tests for react
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved

#958 [fix] changed several tests to react
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/AbstractUiElementsList.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/actions/ListAction.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/PeriodicSql.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
Labels: approved, status/review-requested

#959 [UI] fix gmail (and maybe more) connection creation in firefox on react UI
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
Labels: approved

#962 [ui][fix] fix customization page navigation
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
Labels: approved, status/review-requested

#961 [ui][fix] fix invalid swagger feature
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature
Labels: status/review-requested

#947 [ui][fix] fix logout feature
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: status/review-requested

#963 [ui][fix] fix webhook feature
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved, status/review-requested

#964 Dropdowns and DM multiple mappings fix
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
Labels: approved, status/review-requested

#965 [ui][fix] fix api client connectors crud feature
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
Labels: status/review-requested

#966 [REST] Fix datamapper id containing invalid characters
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
Labels: approved, status/review-requested

#967 [FUSEQE-4299] fix databucket tests with new react UI
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved

#932 [ui] - update activity step test according to fix #4181
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/resources/features/other/integration-activity.feature
Labels: approved

#971 Rest tests update
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/resources/features/integration-http-producer.feature
  rest-tests/src/test/resources/features/upgrade-prod.feature
Labels: approved

#975 [FUSEQE-4719] Use htpasswd login for OCP4
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: approved, status/review-requested

#973 [ui][fix] fill connection credentials in lower case by data-testid
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
Labels: approved, status/review-requested

#972 [ui][update] update logout test to use test-id selector
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#976 [ui][update] update oauth steps
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
  ui-tests/src/test/resources/features/other/settings-oauth.feature
Labels: approved, status/review-requested

#968 [ui][fix] fix amq-to-rest and api-client-connector features
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
Labels: approved, status/review-requested

#979 [ui][fix] update logout tests to use new oauth flow
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/other/login-logout.feature
Labels: status/review-requested

#981 [ui][fix] fix connection validation test
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/connections/connections.feature
Labels: approved, status/review-requested

#977 [FUSEQE-4760] Edit box test for current behavior
  rest-tests/src/test/resources/features/integration-box.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
Labels: approved, status/review-requested

#983 [ui]UI tests for Public API and Import/Export feature and migration
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCiCdDialog.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdDialogSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature
  ui-tests/src/test/resources/features/other/publicapi/export-import.feature
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/ConnectionsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/EnvironmentsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved, status/review-requested

#970 [ui][fix] activity and metrics feature migration
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/getridof/AbstractStep.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
Labels: approved, status/review-requested

#985 [ui] fixed oauth tests
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved

#986 [ui][fix] update support page tests
  ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/AboutPageSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved, status/review-requested

#988 fix slack tests
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved
