Repository syndesisio/syndesis-qe, pull requests merged in 2019-05, with the labels that each got.

#898 [Account] Fix getting the account using the enum
  utilities/src/main/java/io/syndesis/qe/accounts/AccountsDirectory.java
Labels: approved, status/review-requested

#899 [ui][fix] fix integration import-edit scenario
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/integrations/import-edit-integration-export.zip
Labels: approved, status/review-requested

#897 PublicApi oauth Template, service account, endpoints for Public API
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/ConnectionsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/PublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
Labels: approved, backport master, status/review-requested

#902 [HTTP] Fix step name after refactoring
  rest-tests/src/test/resources/features/integration-http-producer.feature
Labels: approved, status/review-requested

#903 Mark skipped tests in mail report
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
Labels: approved, status/review-requested

#904 [README] Fix for syntax
  README.md
Labels: approved

#887 odata connector smoke and reproducer tests
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java
  ui-tests/src/test/resources/features/integrations/odata.feature
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java
  utilities/src/main/resources/templates/syndesis-wildfly.yml
Labels: approved, backport master, status/review-requested

#906 [Connections] Refactor creating connections
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
Labels: approved, status/review-requested

#907 [FUSEQE-4065] Add SQS tests
  README.md
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/extension/ExtensionHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/IntermediateSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
  rest-tests/src/test/resources/extensions/set-sqs-group-id-extension-1.0-SNAPSHOT.jar
  rest-tests/src/test/resources/features/integration-sqs.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SQSValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/StepDescriptorEndpoint.java
  utilities/src/main/java/io/syndesis/qe/utils/SQSUtils.java
Labels: approved, status/review-requested

#901 REST tests for PublicAPI and export/import
  README.md
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/ConnectionsPublicApiSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/IntegrationsPublicApiSteps.java
  rest-tests/src/test/resources/features/publicapi/connections.feature
  rest-tests/src/test/resources/features/publicapi/environments.feature
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/Verifier.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, backport master

#909 [ui][new] allow to set webdriver version from maven command to support older browsers
  README.md
  pom.xml
  ui-tests/pom.xml
Labels: approved, status/review-requested

#911 [Drivers] Bind drivers download to install phase
  ui-tests/pom.xml
Labels: approved

#905 [Checkstyle] Use prepare-commit-msg hook for checkstyle
  .circleci/config.yml
  README.md
  checkstyle.xml
  checkstyle/checkstyle.xml
  checkstyle/intellij-settings.jar
  hooks/prepare-commit-msg
  pom.xml
Labels: approved

#917 Add annotations for tests affected by gh-5332
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved

#919 [FUSEQE-4416] Fix @api-provider-post-collection
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/swagger/connectors/collection.json
Labels: approved, status/review-requested

#922 [ui][fix] fix ambiguous button titles
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
  ui-tests/src/test/resources/features/quickstarts/hello-world.feature
Labels: approved, status/review-requested

#918 [ui][fix] fix split-aggregate flow
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
Labels: approved, status/review-requested

#920 Browsers 1.6.x
  README.md
  pom.xml
  ui-tests/pom.xml
Labels: status/review-requested

#924 Mark skipped tests in mail report
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
Labels: approved, status/review-requested

#923 [ui][tags] add github issue tags for apicurio security bug
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: status/review-requested

#916 [FUSEQE-4209] gherkin scenario for email connectors
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/email.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/template.feature
Labels: approved

#921 [refactor] refactor salesforce validation steps
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/SalesforceAccount.java
Labels: approved, status/review-requested

#927 [DB] Refactor to DB collection in datamapper
  rest-tests/src/test/resources/features/integration-monitoring.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/smoke.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
Labels: approved, status/review-requested

#928 [Upgrade] Temporary ignore upgrade tests
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
Labels: approved, status/review-requested

#926 [FUSEQE-4426] updated scenario to test starttls (smtp) and pop3 for email connector
  ui-tests/src/test/resources/features/integrations/email.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
Labels: approved, status/review-requested

#929 [checkstyle] Tweak checkstyle, prevent bypassing by not staging
  checkstyle/checkstyle.xml
  hooks/prepare-commit-msg
Labels: approved, status/review-requested

#925 [S3] Change account name to AWS
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/ConnectionSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
Labels: approved, status/review-requested

#930 [FUSEQE-4498] fix tests with sql connector mapping collections
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
Labels: approved

#931 [Checkstyle] Add rules for static imports
  checkstyle/checkstyle.xml
Labels: approved, status/review-requested

#914 Reproducer for gh-4466: SQL connector should return generated keys
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#934 [FUSEQE-4099] Add DB stored procedures test
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/resources/features/integration-database.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsActionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
Labels: approved, status/review-requested

#937 [Exporter] Use tech preview namespace for exporter
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  template/generate.sh
Labels: approved, backport master, status/review-requested

#942 [Upgrade] Use pull secret
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, backport master, status/review-requested
