Repository syndesisio/syndesis-qe, pull requests merged in 2019-04, with the labels that each got.

#837 [ui][sql] Copypasta to have clean test report
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#838 [ui][sql] Add tests for SQL predicates - master
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved, status/review-requested

#839 [GitHub] Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, backport 1.6.x

#830 [FUSEQE-3678] Add INFRA_ONLY + some changes for jenkins
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, backport 1.6.x, backport master, status/review-requested

#843 fix @tech-extension-create-integration-with-new-tech-extension
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
Labels: approved, backport 1.6.x

#842 Fuseqe 3678 prod upgrade 1.6.x
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, backport master, status/review-requested

#836 Fix @create delete api connector
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
Labels: backport master

#847 [ui][update] update data buckets tests
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, backport master, status/review-requested

#841 [FUSEQE-3330] Rebuild integration after prod upgrade
  rest-tests/src/test/resources/features/upgrade-prod.feature
Labels: approved, backport master

#851 [ui][fix] stabilize 3scale annotation test
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/resources/features/other/3scale.feature
Labels: approved, backport master, status/review-requested

#850 [ui][fix] fix integration import-export scenarios
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
Labels: approved, backport master, status/review-requested

#855 [ui][fix] stabilize api connector test
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
Labels: approved, backport master, status/review-requested

#860 [POM] Bump activemq version
  pom.xml
Labels: approved

#814 [api-provider] Fix failing tests and introduce new ones 1.6.x
  ui-tests/pom.xml
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/ApiProviderOperationEditorPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#857 [FUSEQE-3217] rest aggregate
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/DataMapperSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/IntermediateSteps.java
  rest-tests/src/test/resources/features/integration-aggregate.feature
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/entities/DataMapperDefinition.java
  utilities/src/main/java/io/syndesis/qe/bdd/entities/DataMapperStepDefinition.java
Labels: approved, status/review-requested

#863 [POM] Fix maven clashes
  pom.xml
  rest-tests/pom.xml
  ui-tests/pom.xml
  utilities/pom.xml
Labels: approved, status/review-requested

#864 [ui][fix] Fix my blunder of renaming AddToIntegration
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/AddToIntegration.java
Labels: approved, backport master, status/review-requested

#866 [ui] Skip apicurito standalone tests
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
Labels: approved, backport master, status/review-requested

#781 [ui] - reproducer for #gh-4182
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/InvokeSql.java
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/integrations/webhook-db.feature
Labels: approved

#751 Template
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/getridof/AbstractStep.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/getridof/StepFactory.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/TemplateSteps.java
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/templates/mustache.tpl
Labels: approved, status/review-requested

#854 [UI][fix] - test fix for gh-5100
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
Labels: approved, backport 1.6.x

#868 add stage smoke to 1.6.x branch
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#869 add stage-smoke to master
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#835 [google-sheets] fix tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/integrations/service-now.feature
  utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
Labels: approved, backport master, status/review-requested

#834 [ui] Tests for OAuth connectors
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved, status/review-requested

#871 [Hooks] Add pre-push hook
  README.md
  hooks/pre-push
Labels: approved, status/review-requested

#872 [Rollback] Add gh issue annotation
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
Labels: approved, status/review-requested

#874 [Upgrade] Don't manually modify s2i tag
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
Labels: approved, status/review-requested

#875 [ui][fix] stabilize support page and data buckets tests
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/ConnectionActionSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, backport master, status/review-requested

#878 [google-sheets] fix test failing due to added new page in connector
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved

#877 Add cucumber formatter for mail report
  rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
  utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
  utilities/src/main/java/io/syndesis/qe/issue/IssueState.java
  utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java
Labels: approved, backport master, status/review-requested

#883 [ui][fix] Fix Google Calendar get event test
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, backport master, status/review-requested

#885 [FUSEQE-3726] Add reproducer for GH-5093
  rest-tests/src/test/resources/features/integration-http-producer.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#881 [FUSEQE-3292] Use AMQ Streams 1.1.0
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/resources/kafka/kafka-ephemeral.yaml
  utilities/src/main/resources/kafka/strimzi-cluster-operator-0.8.2.yaml
  utilities/src/main/resources/kafka/strimzi-deployment.yaml
Labels: approved, status/review-requested

#880 [FUSEQE-3823] Add box connector tests
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
  rest-tests/src/test/resources/features/integration-box.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
Labels: approved, status/review-requested

#888 [FUSEQE-3845] Add check for prod build integrations
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/resources/features/check-prod-versions.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ProdValidationSteps.java
Labels: approved, backport 1.6.x, status/review-requested

#889 [ui, rest][refactor] refactor database validation steps
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/smoke.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, backport master, status/review-requested

#893 [ui][fix] fail the validation step when result set thorws an exception
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, backport master, status/review-requested

#892 [ui, rest][refactor] update database validation steps
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/smoke.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#882 [ui][fix] fix integration import-export scenarios
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
Labels: approved, status/review-requested

#894 [ui][fix] fail the validation step when result set thorws an exception
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#895 [Upgrade] Fix missing file copy
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#896 [Accounts] Use enum for account names
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/accounts/AccountsDirectory.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
  utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
  utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
  utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
  utilities/src/main/java/io/syndesis/qe/utils/TelegramUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/mqtt/MqttUtils.java
Labels: approved, status/review-requested

#886 [DB] Slight refactor of DB things
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
Labels: approved, status/review-requested
