Repository syndesisio/syndesis-qe, pull requests merged in 2019-03, with the labels that each got.

#740 [FUSEQE-2976] Prod upgrade - add file that exports the variables
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, status/review-requested

#744 [install] increase timeout when cleaning syndesis namespace
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved, status/review-requested

#745 [ui][fix] remove outdated step in concur feature
  ui-tests/src/test/resources/features/integrations/concur.feature
Labels: approved, status/review-requested

#743 [FUSEQE-3321] Switch branches when doing upgrade
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
Labels: approved, status/review-requested

#742 Fuseqe 3321 1.5.x
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
  rest-tests/src/test/resources/upgrade/prod/vars
Labels: approved, status/review-requested

#741 Fuseqe 3321 1.4.x
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationSteps.java
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
  rest-tests/src/test/resources/upgrade/prod/vars
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
Labels: approved, status/review-requested

#747 [ui][update] Update activity/metrics (reproducer for gh-4162)
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
Labels: approved

#746 [service-now] fix tests by changing ids
  ui-tests/src/test/resources/features/integrations/service-now.feature
Labels: approved, status/review-requested

#734 [google-sheets] add google sheets connector tests
  pom.xml
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleSheetsValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/GoogleAccount.java
  utilities/src/main/java/io/syndesis/qe/utils/GoogleAccounts.java
  utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
Labels: approved, status/review-requested

#739 [ui][fix] fix logout tests to reflect UI changes
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, status/review-requested

#750 [FUSEQE-3430] Print pods when something bad happens
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#749 Fuseqe 3398 refactor upgrade
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  ui-tests/pom.xml
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
Labels: approved

#755 [FUSEQE-3493] Bump postgresql version
  pom.xml
Labels: approved, status/review-requested

#756 [FUSEQE-3493] Bump postgresql version
  pom.xml
Labels: approved, status/review-requested

#754 [FUSEQE-3330] Rebuild integration after upgrade 1.6.x
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#753 [FUSEQE-3330] Rebuild integration after upgrade
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved, status/review-requested

#758 [Upgrade] Fix floating point issues + deploy using operator 1.6
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved, status/review-requested

#757 Upgrade split
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#759 [ui][update] OAuth tests now validate every connector with OAuth 1.6.x
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: status/review-requested

#760 [ui][update] OAuth tests now validate every connector with OAuth
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: status/review-requested

#763 [Undeploy] Don't fail when can't parse json response
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#764 Undeploy syndesis 1.6
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#765 [ui][fix] fix apicurio tests 16x
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: approved, status/review-requested

#766 [ui][fix] fix apicurio tests
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: approved, status/review-requested

#769 [ui][fix] navigate to integrations page when validating integration status 16x
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
Labels: approved, status/review-requested

#770 [ui][fix] navigate to integrations page when validating integration status
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
Labels: approved, status/review-requested

#772 [ui][disable] disable concur tests 16x
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
Labels: approved, status/review-requested

#771 [ui][disable] disable concur tests
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
Labels: approved, status/review-requested

#768 Fuseqe 3537 prod template 1.6
  template/prod.template.yml
Labels: approved, status/review-requested

#773 Fix dropbox
  rest-tests/src/test/resources/features/file-transfer.feature
  rest-tests/src/test/resources/features/integration-monitoring.feature
  rest-tests/src/test/resources/features/integration-s3-to-s3.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  rest-tests/src/test/resources/features/irc.feature
  utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
Labels: approved, status/review-requested

#774 Fix dropbox 1.6
  utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
Labels: approved, status/review-requested

#767 [FUSEQE-3537] Add latest operator dc
  template/prod.template.yml
Labels: approved, status/review-requested

#762 AMQ to REST jenkins fix
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved

#777 [ui][fix] fix apicurio operation remove test 16x
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Labels: approved, status/review-requested

#761 [ui][new] kudu connector test 16x
  ui-tests/src/test/java/io/syndesis/qe/steps/other/KuduSteps.java
  ui-tests/src/test/resources/features/integrations/kudu.feature
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduTemplate.java
  utilities/src/main/resources/templates/syndesis-kudu.yml
Labels: status/review-requested

#737 [ui][new] kudu connector test
  ui-tests/src/test/java/io/syndesis/qe/steps/other/KuduSteps.java
  ui-tests/src/test/resources/features/integrations/kudu.feature
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/KuduTemplate.java
  utilities/src/main/resources/templates/syndesis-kudu.yml
Labels: status/review-requested

#779 [FUSEQE-3527] Unify bash scripts approach
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  template/generate.sh
  template/vars
Labels: approved

#778 [FUSEQE-3527] Unify bash scripts approach
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  template/generate.sh
  template/vars
Labels: approved, status/review-requested

#776 [ui][fix] fix apicurio operation remove test
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Labels: approved, status/review-requested

#775 Add split/aggregate tests
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
Labels: status/review-requested

#785 [ui][fix] swap simple logger for just log connector
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
Labels: approved

#784 [ui][fix] swap simple logger for just log connector 16x
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
Labels: approved

#783 [ui][fix] change to log connector in kudu tests due to removal of log step
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, status/review-requested

#787 [ui][new] extend log connector tests
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/log-connector.feature
Labels: status/review-requested

#788 [ui] 1.6.x split/aggregate steps
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
Labels: approved, status/review-requested

#789 [ui][new] extend log connector tests 17x
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/log-connector.feature
Labels: approved

#792 [Upgrade] Skip upgrade tests with prod version
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
Labels: approved, status/review-requested

#791 [Upgrade] Skip upgrade tests with prod version
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
Labels: approved, status/review-requested

#790 Refactor binary client
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#782 [ui][fix] change to log connector in kudu tests due to removal of log step 16x
  ui-tests/src/test/resources/features/integrations/kudu.feature
Labels: approved, status/review-requested

#794 [FUSEQE-3679] Remove chars that cause problems when parsing
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/irc.feature
Labels: approved

#793 [FUSEQE-3679] Remove chars that cause problems when parsing
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/irc.feature
Labels: approved, status/review-requested

#796 [ui][fix] kudu tests - do not fail with empty pod logs
  utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#795 [ui][fix] kudu tests - do not fail with empty pod logs 16x
  utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#798 [ui][fix] fix webhook test
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved

#797 [ui][fix] fix webhook test 16x
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Labels: approved

#800 [ui][fix] fix dataBucket tests
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#799 [ui][fix] fix dataBucket tests 16x
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved, status/review-requested

#801 [ui][fix] tw to sf test fix 1.6.x
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
Labels: approved

#806 [ui][fix] fix slack tests 16x
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved

#812 fix @tech-extension-create-integration-with-new-tech-extension
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
Labels: approved

#808 [ui][fix] fix 3scale tests 16x
  ui-tests/src/test/resources/features/other/3scale.feature
Labels: approved

#817 fix api-client-connector
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
Labels: approved, status/review-requested

#818 [ui][fix] open data mapper collections before mapping starts 16x
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
Labels: status/review-requested

#821 [Generator] Fix for current version
  template/generate.sh
  template/prod.template.yml
  template/vars
Labels: approved

#822 [Generator] Fix for current version
  template/generate.sh
  template/prod.template.yml
  template/vars
Labels: approved

#809 [ui][fix] fix 3scale tests
  ui-tests/src/test/resources/features/other/3scale.feature
Labels: approved

#824 [ui][fix] fix import edit test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/import-edit.feature
Labels: approved

#825 [ui][fix] fix import edit test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/import-edit.feature
Labels: approved

#826 [AMQ] Remove service created by operator if present
  utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
Labels: approved

#832 [doc] added script to generate list of step definitions
  README.md
  docs/generateDocs.py
Labels: approved

#833 [FUSEQE-3680] Fix failing salesforce tests
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
Labels: approved, status/review-requested
