Repository syndesisio/syndesis-qe, pull requests merged in 2019-01, with the labels that each got.

#594 Integration import export without salesforce
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/integrations/Imported-integration-another-instance-export.zip
Labels: approved, status/review-requested

#678 [ui][new] rewrite default timeout for selenide collection operations
  README.md
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved

#679 [ActiveMQ] Bump ActiveMQ version
  pom.xml
Labels: approved, status/review-requested

#681 [FUSEQE-2738] Verify connections before creating integration in REST …
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
  utilities/src/main/java/io/syndesis/qe/endpoints/Verifier.java
Labels: approved, status/review-requested

#677 Extend Metrics test about testing uptime and start date
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
  ui-tests/src/test/resources/features/other/integration-metrics.feature
Labels: approved, status/review-requested

#686 Allow to skip tests with open issues
  README.md
  ui-tests/src/test/java/io/syndesis/qe/hooks/IssueHooks.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#689 [ui-tests] Fix data-bucket tests
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
Labels: approved

#688 [FUSEQE-2893] Fix UI tests after UI changes
  ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
  ui-tests/src/test/resources/features/other/3scale.feature
Labels: approved

#694 Create db-2-db quckstart test
  ui-tests/pom.xml
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
Labels: approved

#691 [Refactor] Refactor REST tests to use common method for creating conn…
  pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/ActiveMQSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/DataMapperSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/DatabaseSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/DropboxSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/FTPSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/FilterSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/HTTPSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IrcSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/KafkaSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/LogSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/S3Steps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/SalesforceSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/TwitterSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
  rest-tests/src/test/resources/features/file-transfer.feature
  rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
  rest-tests/src/test/resources/features/integration-http-consumer.feature
  rest-tests/src/test/resources/features/integration-http-producer.feature
  rest-tests/src/test/resources/features/integration-kafka.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  rest-tests/src/test/resources/features/irc.feature
  rest-tests/src/test/resources/features/soak-deployment.feature
  rest-tests/src/test/resources/features/timer-connector.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
  ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  ui-tests/src/test/resources/features/integrations/service-now.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
  utilities/pom.xml
  utilities/src/main/java/io/syndesis/qe/bdd/AbstractStep.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/IrcValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/HTTPEndpointsTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/IrcTemplate.java
  utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestConstants.java
Labels: status/review-requested

#673 [ui-tests] Add import-edit integration test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/integrations/import-edit-integration-export.zip
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
Labels: approved

#698 chore: remove unused imports
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/WizardPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/SelectConnectionType.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/NameConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsMetricsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/utils/GoogleAccount.java
Labels: approved

#699 [UI] Remove obsolete protractor tests
  ui-tests-protractor/.yarnclean
  ui-tests-protractor/LICENSE
  ui-tests-protractor/angular-cli.json
  ui-tests-protractor/e2e-xvfb.sh
  ui-tests-protractor/e2e/common/common.ts
  ui-tests-protractor/e2e/common/utils.ts
  ui-tests-protractor/e2e/common/world.ts
  ui-tests-protractor/e2e/conf/protractor.base.conf.js
  ui-tests-protractor/e2e/conf/protractor.local.conf.js
  ui-tests-protractor/e2e/conf/protractor.syndesis-qe.conf.js
  ui-tests-protractor/e2e/data/datamapper-integration-base.json
  ui-tests-protractor/e2e/env.ts
  ui-tests-protractor/e2e/features/connections/connections.feature
  ui-tests-protractor/e2e/features/dashboard/dashboard.feature
  ui-tests-protractor/e2e/features/integrations/basic-filter.feature
  ui-tests-protractor/e2e/features/integrations/delete-integrations.feature
  ui-tests-protractor/e2e/features/integrations/detail-page-integrations.feature
  ui-tests-protractor/e2e/features/integrations/integrations-sf-db.feature
  ui-tests-protractor/e2e/features/integrations/kebab-integrations.feature
  ui-tests-protractor/e2e/features/integrations/multiple-steps-integrations.feature
  ui-tests-protractor/e2e/features/integrations/twitter-search.feature
  ui-tests-protractor/e2e/features/integrations/twitter-to-salesforce-integration.feature
  ui-tests-protractor/e2e/features/screenshots/screenshots.feature
  ui-tests-protractor/e2e/features/settings/settings.feature
  ui-tests-protractor/e2e/page-objects/app.po.ts
  ui-tests-protractor/e2e/page-objects/connections/detail/detail.po.ts
  ui-tests-protractor/e2e/page-objects/connections/edit/edit.po.ts
  ui-tests-protractor/e2e/page-objects/connections/list/list.po.ts
  ui-tests-protractor/e2e/page-objects/dashboard/dashboard.po.ts
  ui-tests-protractor/e2e/page-objects/integrations/detail/detail.po.ts
  ui-tests-protractor/e2e/page-objects/integrations/edit/datamapper.po.ts
  ui-tests-protractor/e2e/page-objects/integrations/edit/edit.po.ts
  ui-tests-protractor/e2e/page-objects/integrations/list/list.po.ts
  ui-tests-protractor/e2e/page-objects/login/login.po.ts
  ui-tests-protractor/e2e/page-objects/settings/settings.po.ts
  ui-tests-protractor/e2e/steps/common.steps.ts
  ui-tests-protractor/e2e/steps/connections/connections.steps.ts
  ui-tests-protractor/e2e/steps/integrations/datamapper.steps.ts
  ui-tests-protractor/e2e/steps/integrations/integration.steps.ts
  ui-tests-protractor/e2e/steps/screenshots/screenshots.steps.ts
  ui-tests-protractor/e2e/steps/settings/settings.steps.ts
  ui-tests-protractor/e2e/tsconfig.json
  ui-tests-protractor/package.json
  ui-tests-protractor/protractor.conf.js
  ui-tests-protractor/src/app/logging.ts
  ui-tests-protractor/src/tsconfig.json
  ui-tests-protractor/tslint.json
  ui-tests-protractor/upgrade-dependencies.sh
  ui-tests-protractor/yarn.lock
Labels: approved, status/review-requested

#700 chore: configurable browser binary path
  ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved

#702 [Readme] Update readme
  README.md
Labels: approved, status/review-requested

#701 [REST] Unify scenario names
  rest-tests/src/test/resources/features/file-transfer.feature
  rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
  rest-tests/src/test/resources/features/integration-http-consumer.feature
  rest-tests/src/test/resources/features/integration-http-producer.feature
  rest-tests/src/test/resources/features/integration-kafka.feature
  rest-tests/src/test/resources/features/integration-s3-to-s3.feature
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  rest-tests/src/test/resources/features/irc.feature
  rest-tests/src/test/resources/features/smoke.feature
  rest-tests/src/test/resources/features/timer-connector.feature
Labels: approved, status/review-requested
