Repository syndesisio/syndesis-qe, pull requests merged in 2019-02, with the labels that each got.

#703 Fixes after UI changes
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseConnection.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
  ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
  ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/service-now.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/telegram.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/other/3scale.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
  ui-tests/src/test/resources/features/other/support-page.feature
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
  ui-tests/src/test/resources/features/quickstarts/hello-world.feature
  ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
Labels: approved

#704 [Upgrade] Use scripts from minorVersion during daily upgrade
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
Labels: approved, status/review-requested

#706 [GH-4308] Temporary disable all tests with extensions
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
Labels: approved, status/review-requested

#707 [README] Update PR test notation
  README.md
Labels: approved, status/review-requested

#710 [Operator] Revert back to pre-SSO operator deployment
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#711 [REST] Fix Twitter to Salesforce ids
  rest-tests/src/test/resources/features/integration-tw-sf.feature
  rest-tests/src/test/resources/features/smoke.feature
Labels: approved

#709 [FUSEQE-2589] Fix for prod template + add generator
  Jenkinsfile
  run-tests.sh
  template/generate.sh
  template/prod.template.yml
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: approved, status/review-requested

#705 [FUSEQE-2976] Automate prod upgrade procedure
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
  rest-tests/src/test/resources/upgrade/prod/resources.yml
Labels: approved, status/review-requested

#714 [ui][fix] fix concur scenario
  ui-tests/src/test/resources/features/integrations/concur.feature
Labels: approved

#712 [FUSEQE-3045] Temporary edit upgrade tests
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
Labels: approved, status/review-requested

#713 Rest fixes
  rest-tests/src/test/resources/features/integration-sf-db.feature
  rest-tests/src/test/resources/features/integration-sf-producers.feature
  utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Labels: approved

#716 [ui][fix] fix data mapper card and action selection
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java
Labels: approved, status/review-requested

#717 [ui][fix] change save button name
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/telegram.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/other/support-page.feature
Labels: approved, status/review-requested

#718 [ui][fix] fix data mapper collection mappings
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
Labels: approved, status/review-requested

#719 Fix enabling test support
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#722 [HTTPEndpoints] Add wait for HTTP endpoints
  utilities/src/main/java/io/syndesis/qe/templates/HTTPEndpointsTemplate.java
Labels: approved, status/review-requested

#723 [FUSEQE-3209] Fix new plural form of syndesis resource
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#720 [Deploy] Avoid infinite loop while waiting for image streams
  utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
Labels: approved, status/review-requested

#726 Fuseqe 3109 split aggregate
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/SplitSteps.java
  rest-tests/src/test/resources/features/integration-monitoring.feature
  rest-tests/src/test/resources/features/smoke.feature
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
  rest-tests/src/test/resources/features/upgrade-syndesis.feature
  utilities/src/main/java/io/syndesis/qe/bdd/AbstractStep.java
  utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/StepDescriptorEndpoint.java
Labels: status/review-requested

#727 [Smoke] Fix UI smoke
  ui-tests/src/test/resources/features/connections/connections.feature
Labels: approved, status/review-requested

#708 Update activity test according to gh-4407
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/resources/features/other/integration-activity.feature
Labels: approved

#729 [Undeploy] Remove all syndesis CRDs during undeployment
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#730 created SQL connector reproducer test for gh-3856
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
Labels: approved

#731 Maintainers
  rest-tests/src/test/resources/features/integration-monitoring.feature
  rest-tests/src/test/resources/features/soak-deployment.feature
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
Labels: approved, status/review-requested

#732 [ui][fix] fix support page tests to reflect UI update
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: status/review-requested

#733 Revert "[Undeploy] Remove all syndesis CRDs during undeployment"
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#735 [FUSEQE-3209] Revert plural syndesis form
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved, status/review-requested

#736 [FUSEQE-3285] Add tags to the integrations created in REST suite
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
Labels: approved, status/review-requested

#721 Versions
  pom.xml
  rest-tests/pom.xml
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/DataMapperSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/FTPSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/LogSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/SalesforceSteps.java
  ui-tests/pom.xml
  ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/NameConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/WizardSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/CreateIntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConfigureStepSteps.java
  utilities/pom.xml
  utilities/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
  utilities/src/main/java/io/syndesis/qe/bdd/utils/GoogleCalendarSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DropBoxValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleCalendarValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/DatatableUtils.java
Labels: approved, status/review-requested

#738 [ui][fix][FUSEQE-3282] make scenario names unique
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
Labels: approved, status/review-requested
