Repository syndesisio/syndesis-qe, pull requests merged in 2020-03, with the labels that each got.

#1356 [camel-k] Added test for disabled API client
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/other/camelk.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1351 [FUSEQE-8028][FUSEQE-8013] - Change default CR and enable Jaeger
  rest-tests/src/test/resources/features/operator-deployment.feature
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
  ui-tests/src/test/resources/features/other/integration-activity.feature
  ui-tests/src/test/resources/features/other/integration-metrics.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
Labels: approved

#1360 [fix] Added description to scenario
  ui-tests/src/test/resources/features/other/camelk.feature
Labels: approved

#1350 [FUSEQE-6148] added list of all issues that affected the test run
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
  utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java
Labels: approved

#1362 [FUSEQE-8265] - Update service for AMQ broker
  ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
  utilities/src/main/resources/templates/syndesis-amq.yml
  utilities/src/main/resources/templates/syndesis-default-amq-service.yml
Labels: approved

#1361 [fix] Increase timer default time - to achieve more stable results
  rest-tests/src/test/resources/features/timer-connector.feature
Labels: approved

#1364 [Report] Remove <li> elements from the report
  utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
Labels: approved

#1365 [FIX] Fix amq auto detecting
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
Labels: approved

#1319 dv smokes
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/VirtualizationList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java
  ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java
  ui-tests/src/test/resources/features/other/data-virtualization.feature
  utilities/src/main/java/io/syndesis/qe/resource/impl/DV.java
Labels: approved

#1366 [FUSEQE-8269] Use regular user for manipulating the CR
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/PreviousSyndesis.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1265 [FUSEQE-3846] Automated Fuse Online test to verify whether the docs h…
  ui-tests/src/test/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
  ui-tests/src/test/resources/features/other/docs-verification.feature
Labels: approved

#1370 [Fixes] Use our broker in prod build + dont catch all exceptions in u…
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
Labels: approved

#1371 [Operator] Fix DV scenarios
  rest-tests/src/test/resources/features/operator-deployment.feature
Labels: approved

#1372 [FUSEQE-8265] Use different account for AMQ to REST test
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
  utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java
Labels: approved

#1373 [Monitoring] Edit test to work with Jaeger
  rest-tests/src/test/resources/features/integration-monitoring.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
Labels: approved

#1374 Log improvement
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
Labels: approved

#1375 [FUSEQE-8506] changed prod test to actually test for the exact value
  rest-tests/src/test/resources/features/check-prod-versions.feature
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/ProdValidationSteps.java
Labels: approved

#1369 [fix] Change runtime in CamelK#undeploy and Jaeger deploy
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#1377 Hotfix for Jaeger workarounds
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1376 [Operator] Add missing repository to deployIntegrations test
  rest-tests/src/test/resources/operator/spec/components/server/deployIntegrations.yml
Labels: approved, size/XS

#1378 Enable Jaeger in the PR job
  utilities/src/main/resources/syndesis-minimal.yaml
Labels: approved, size/XS

#1381 Hopefully QoL changes
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/test/InfraFail.java
  utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved

#1330 [FUSEQE-2178] create import/export tests with OpenAPI re…
  ui-tests/src/test/resources/features/integrations/integration-import-export-open-api.feature
Labels: approved

#1386 [Upgrade] Check CR status and don't rely on logs
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
Labels: approved

#1382 [FIX] Fix of @oauth-gcalendar test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: size/XS

#1383 [FUSEQE-8363] SFTP test stabilization
  utilities/src/main/java/io/syndesis/qe/utils/SftpClientManager.java
  utilities/src/main/java/io/syndesis/qe/utils/SftpUtils.java
Labels: approved

#1385 Log connector fixes
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
Labels: review-requested

#1368 [FUSEQE-8020] - add external jaeger test
  rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
  rest-tests/src/test/resources/features/operator-deployment.feature
  rest-tests/src/test/resources/jaeger/jaeger-service-collector.yml
  rest-tests/src/test/resources/jaeger/jaeger-service-query.yml
  rest-tests/src/test/resources/jaeger/jaeger.yml
  rest-tests/src/test/resources/operator/spec/addons/external-jaeger.yml
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1387 [Deploy] Print exception to debug when user doesn't have admin rights
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Labels: review-requested

#1384 [fix] don't crash on non-existing label
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
Labels: approved

#1379 [fix] used Syndesis#ensureImagePull for Camel K
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
Labels: approved, commented
