Repository syndesisio/syndesis-qe, pull requests merged in 2020-05, with the labels that each got.

#1461 [FUSEQE-8681] Fix extension delete test
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
Labels: approved

#1460 Fixed conditional flow steps
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
  ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
Labels: approved

#1462 [FUSEQE-8681] Fix integrations-check test
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/resources/features/integrations/api-provider.feature
Labels: approved

#1464 Fix "check there are (\d*) integration steps"
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
Labels: approved

#1465 [FUSEQE-8681] Fix template stale element
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java
Labels: approved

#1463 [FUSEQE-8681] - backports PF4 changes
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
  ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java
  ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
Labels: approved

#1469 [FUSEQE-8675] Fix testsuite to syndesis 2.0 part 2
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved

#1471 [FUSEQE-8862] DataMapper migration
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/api-provider.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/data-mapper.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export-open-api.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/jira.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/odata.feature
  ui-tests/src/test/resources/features/integrations/openapi.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
  ui-tests/src/test/resources/features/integrations/webhook-db.feature
  ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
Labels: approved

#1470 [FUSEQE-8675] Fix testsuite to syndesis 2.0 part 2
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: approved, backport master

#1472 [Box] Fix s3-box scenario
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/resources/features/integration-box.feature
  rest-tests/src/test/resources/features/integration-s3-to-s3.feature
  utilities/src/main/java/io/syndesis/qe/utils/FileTansferUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/FileTransferUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/SftpUtils.java
Labels: approved

#1475 Fix box
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/resources/features/integration-box.feature
  rest-tests/src/test/resources/features/integration-s3-to-s3.feature
  utilities/src/main/java/io/syndesis/qe/utils/FileTansferUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/FileTransferUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/SftpUtils.java
Labels: approved

#1424 [FUSEQE-1450] Add HTTPS connector tests
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
  rest-tests/src/test/resources/features/integration-http-consumer.feature
  rest-tests/src/test/resources/features/integration-http-producer.feature
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/HTTPEndpoints.java
Labels: approved

#1477 [fix] added test ids to choose api method page
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
Labels: approved

#1480 [backport][fix] added test ids to choose api method page
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
Labels: approved

#1479 [ResetDB] Reset DV when it is present
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
Labels: approved

#1478 [ResetDB] Reset DV when it is present
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
Labels: review-requested

#1481 [FUSEQE-8862] Support for fields with the same name in DataMapper
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
Labels: approved

#1476 [Deploy] Use new variable names for images
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1484 [Upgrade] Sort tags before selecting the latest one
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
Labels: approved

#1482 [FUSEQE-8862] Support for fields with the same name in DataMapper
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/other/integration-activity.feature
Labels: backport master, review-requested

#1474 [FIX] Fix sveres testsuite
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Labels: backport 1.9.x, review-requested

#1488 Add DataTestId to the Api review page
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Labels: approved

#1413 [FUSEQE-5584] Test maximum number of integrations
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
  ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: commented, review-requested

#1450 [FUSEQE-5584] Test maximum number of integrations
  ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
  ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved, backport master

#1467 [FUSEQE-3846] update (7.7 added to versions)
  ui-tests/src/test/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
  ui-tests/src/test/resources/features/other/docs-verification.feature
Labels: approved

#1468 [FUSEQE-3846] Backport to master
  ui-tests/src/test/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
  ui-tests/src/test/resources/features/other/docs-verification.feature
Labels: approved

#1491 [FUSEQE-8553] Disconnected install
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
  rest-tests/src/test/resources/features/disconnected-install.feature
  rest-tests/src/test/resources/features/integration-kafka.feature
  ui-tests/src/test/java/io/syndesis/qe/steps/other/KuduSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/odata.feature
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/Resource.java
  utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/DV.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/ExternalDatabase.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/FTP.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/HTTPEndpoints.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/IRC.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Kafka.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Kudu.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/MongoDb36.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/SFTP.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/WildFlyS2i.java
  utilities/src/main/java/io/syndesis/qe/utils/DynamoDbUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java
  utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
Labels: approved

#1495 Fix enabling test support on operator DC
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: approved

#1493 Fix enabling test support on operator DC
  utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
  utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
Labels: backport master

#1496 [FUSEQE-8862] Change datatestid for properties
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
Labels: approved

#1497 [Upgrade] Fix deploying previous released image
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
Labels: approved
