Repository syndesisio/syndesis-qe, pull requests merged in 2020-04, with the labels that each got.

#1395 [FIX] Fix of @integrations-db-to-kafka-to-db
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
Labels: approved

#1397 [FIX] Fix of @integrations-db-to-kafka-to-db
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
Labels: backport 1.9.x

#1396 [FIX] Fix of @integrations-db-to-kafka-to-db
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
Labels: backport master

#1390 [FUSEQE-5957] - Update twitter DM test scenario to support multiple c…
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/twitter/TwitterSend.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConfigureStepSteps.java
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
Labels: approved

#1394 [FUSEQE-8632] openwire and mysql stability improvement
  utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java
  utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Labels: approved

#1402 [Config] Use artifacts from 1.9.x branch
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Labels: approved

#1405 [Operator] Fix checking version for floating tags
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
Labels: review-requested

#1404 [Operator] Fix checking version for floating tags
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
Labels: review-requested

#1403 [Operator] Fix checking version for floating tags
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
Labels: review-requested

#1407 [FUSEQE-8609] Migrate tests to PF4 ui
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/KafkaSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java
  ui-tests/src/test/resources/features/other/integration-info.feature
Labels: approved

#1406 [FUSEQE-8537] Bump amq-streams to 1.4
  utilities/src/main/resources/kafka/kafka-ephemeral.yaml
  utilities/src/main/resources/kafka/strimzi-deployment.yaml
Labels: approved

#1411 Bump Syndesis version
  pom.xml
Labels: approved

#1409 [FUSEQE-8537] Bump amq-streams to 1.4
  utilities/src/main/resources/kafka/kafka-ephemeral.yaml
  utilities/src/main/resources/kafka/strimzi-deployment.yaml
Labels: approved

#1416 [FIX] Support https for public API
  utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
Labels: approved

#1415 Fix upgrade versions master
  pom.xml
  rest-tests/pom.xml
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/syndesis-cr-previous.yaml
  rest-tests/src/test/resources/upgrade/syndesis-crd-previous.yaml
Labels: approved

#1414 [Upgrade] Fix getting previous version
  pom.xml
  rest-tests/pom.xml
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  rest-tests/src/test/resources/features/upgrade-prod.feature
  rest-tests/src/test/resources/upgrade/syndesis-cr-previous.yaml
  rest-tests/src/test/resources/upgrade/syndesis-crd-previous.yaml
Labels: approved

#1363 [FUSEQE-8017] - Dynamic wait until the integration was actual triggered
  ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature
  ui-tests/src/test/resources/features/integrations/api-client-connector.feature
  ui-tests/src/test/resources/features/integrations/concur.feature
  ui-tests/src/test/resources/features/integrations/data-buckets.feature
  ui-tests/src/test/resources/features/integrations/data-mapper.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
  ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
  ui-tests/src/test/resources/features/integrations/db-to-db.feature
  ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
  ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
  ui-tests/src/test/resources/features/integrations/dynamodb.feature
  ui-tests/src/test/resources/features/integrations/email.feature
  ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
  ui-tests/src/test/resources/features/integrations/gmail.feature
  ui-tests/src/test/resources/features/integrations/google-calendar.feature
  ui-tests/src/test/resources/features/integrations/google-sheets.feature
  ui-tests/src/test/resources/features/integrations/import-edit.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/integrations/jira.feature
  ui-tests/src/test/resources/features/integrations/kudu.feature
  ui-tests/src/test/resources/features/integrations/log-connector.feature
  ui-tests/src/test/resources/features/integrations/mongodb.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
  ui-tests/src/test/resources/features/integrations/odata.feature
  ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
  ui-tests/src/test/resources/features/integrations/service-now.feature
  ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature
  ui-tests/src/test/resources/features/integrations/slack.feature
  ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
  ui-tests/src/test/resources/features/integrations/sql-connector.feature
  ui-tests/src/test/resources/features/integrations/template.feature
  ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
  ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
  ui-tests/src/test/resources/features/integrations/webhook-db.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/utils/IntegrationUtils.java
Labels: approved

#1420 [FUSEQE-8609] Migrate tests to PF4 ui
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/KafkaSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java
  ui-tests/src/test/resources/features/other/integration-info.feature
Labels: approved

#1410 [FUSEQE-8537] Bump amq-streams to 1.4
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  utilities/src/main/resources/kafka/kafka-ephemeral.yaml
  utilities/src/main/resources/kafka/strimzi-deployment.yaml
Labels: approved

#1423 [Datamapper] Bump datamapper version
  pom.xml
Labels: approved

#1427 [FUSEQE-8681] pf4 migration - activity, metrics, public api, connecti…
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/configure/ConfigureConnection.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCiCdDialog.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
  ui-tests/src/test/resources/features/other/settings-oauth.feature
Labels: review-requested

#1428 [Operator] Add knative addon smoke test
  rest-tests/src/test/resources/features/operator-deployment.feature
  rest-tests/src/test/resources/operator/spec/addons/knative.yml
Labels: approved

#1429 [Operator] Add knative addon smoke test
  rest-tests/src/test/resources/features/operator-deployment.feature
  rest-tests/src/test/resources/operator/spec/addons/knative.yml
Labels: approved

#1408 [FUSEQE-7950] Create automated tests for ENTESB-12333
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMetricsEndpointSteps.java
  rest-tests/src/test/resources/features/check-operator-version.feature
Labels: approved

#1430 [FUSEQE-8681] pf4 migration - DataTestID for activity, metrics, PublicAPI
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCiCdDialog.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
Labels: approved

#1432 [FUSEQE-8681] pf4 migration - specifySecurity
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
Labels: approved

#1433 [FUSEQE-8675] Fixing testsuite against syndesis 2.0
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetail.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
  ui-tests/src/test/resources/features/connections/oauth.feature
  ui-tests/src/test/resources/features/integrations/mqtt.feature
Labels: backport master, review-requested

#1434 Backport pf4 migration to the master
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/AbstractUiElementsList.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/configure/ConfigureConnection.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCiCdDialog.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
  ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
  ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
  ui-tests/src/test/resources/features/connections/connections.feature
  ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
  ui-tests/src/test/resources/features/integrations/integration-import-export.feature
  ui-tests/src/test/resources/features/other/settings-oauth.feature
Labels: approved

#1398 [FUSEQE-8611] Rework adding custom repo
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1437 [FUSEQE-8611] Rework adding custom repo
  utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
Labels: approved

#1438 [FUSEQE-8681][pf4-migration] Extension page improvement
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
  ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
  ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
Labels: approved, commented

#1441 [FUSEQE-8681][pf4-migration] data virt smoke migration
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/VirtualizationList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java
  ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java
  ui-tests/src/test/resources/features/other/data-virtualization.feature
Labels: approved

#1449 [FUSEQE-8681][pf4-migration] data virt smoke migration
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/VirtualizationList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java
  ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java
  ui-tests/src/test/resources/features/other/data-virtualization.feature
Labels: backport master

#1447 [FUSEQE-8633] Extend PublicApi rest tests
  rest-tests/src/test/resources/features/publicapi/connections.feature
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/ConnectionsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/model/IntegrationOverview.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/ConnectionsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved, backport master

#1446 [FUSEQE-8633] Extend PublicApi rest tests
  rest-tests/src/test/resources/features/publicapi/connections.feature
  rest-tests/src/test/resources/features/publicapi/integrations.feature
  utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/ConnectionsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
  utilities/src/main/java/io/syndesis/qe/model/IntegrationOverview.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/ConnectionsPublicApiSteps.java
  utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
Labels: approved

#1440 [FUSEQE-8681][pf4-migration] Data shapes and conditional flows fixes
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/datashapes.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
Labels: approved

#1453 [FUSEQE-8681][pf4-migration] Backport to master
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
  ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
  ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java
  ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
  ui-tests/src/test/resources/features/integrations/conditional-flow.feature
  ui-tests/src/test/resources/features/integrations/datashapes.feature
  ui-tests/src/test/resources/features/integrations/integration-status.feature
Labels: approved

#1452 [FUSEQE-8681][pf4-migration] apicurio test
  ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
  ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
  ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
Labels: approved

#1442 [Wait] Ignore exceptions in wait
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved

#1455 [Wait] Move catching exceptions to waitFor method
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java
  rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
  ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
  utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
  utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
  utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
Labels: approved

#1443 [FUSEQE-8797] Fix @oauth-gcalendar test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: review-requested

#1445 [FUSEQE-8797] Fix @oauth-gcalendar test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: backport master, review-requested

#1444 [FUSEQE-8797] Fix @oauth-gcalendar test
  ui-tests/src/test/resources/features/connections/oauth.feature
Labels: approved, backport 1.9.x

#1456 [FUSEQE-8681] - prevent form to use stale elements
  rest-tests/src/test/resources/features/publicapi/connections.feature
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
Labels: approved

#1457 [FUSEQE-8681] - prevent form to use stale elements
  rest-tests/src/test/resources/features/publicapi/connections.feature
  ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
  ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
Labels: approved

#1458 Use modal page for deleting steps
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
Labels: review-requested

#1426 [FUSEQE-1450] Add HTTPS connector tests
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
  rest-tests/src/test/resources/features/integration-http-consumer.feature
  rest-tests/src/test/resources/features/integration-http-producer.feature
  utilities/src/main/java/io/syndesis/qe/accounts/Account.java
  utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
  utilities/src/main/java/io/syndesis/qe/resource/impl/HTTPEndpoints.java
Labels: approved

#1454 [Kafka] Add missing parameter
  rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
Labels: approved

#1459 (backport master)Use modal page for deleting steps
  ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
Labels: approved
